---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Perl::Version: 1.011
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM-Spreadsheet
no_index:
  directory:
    - inc
    - t
requires:
  DBD::CSV: 0.36
  Excel::Writer::XLSX: 0.46
  Spreadsheet::ParseExcel: 0.59
  Spreadsheet::ParseExcel::Simple: 0
  Spreadsheet::Read: 0.47
  Spreadsheet::ReadSXC: 0.20
  Spreadsheet::WriteExcel: 2.37
  Spreadsheet::WriteExcel::Simple: 0
  Spreadsheet::WriteExcelXML: 0.13
  Text::CSV: 1.21
  Text::CSV_XS: 0.86
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.07
